program ::= { statement } finish

type ::= "i32" | "i64" | "bool"

declaration ::= type [ "mut" ] ident "{" expr "}"

assignment ::= ident ":=" expr

finish ::= "exit" operand

statement ::= declaration | assignment | if

if ::= "if" expr NL block [ "else" NL block ]

block ::= "{" NL { statement } [ exit NL ] "}" NL

operand ::= ident | number | "true" | "false"

expr ::= arith [ ("==" | "!=") arith ]

arith ::= term { ("+" | "-") term }

term ::= operand { "*" operand }
